//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SheetDetails
    {
        public long sheetDetailsId { get; set; }
        public Nullable<long> sheetId { get; set; }
        public Nullable<long> pId { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<decimal> rate { get; set; }
        public Nullable<System.DateTime> cDate { get; set; }
        public Nullable<System.DateTime> uDate { get; set; }
    
        public virtual tbl_SheetMaster tbl_SheetMaster { get; set; }
        public virtual tbl_ProductMaster tbl_ProductMaster { get; set; }
    }
}
