//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserProfile
    {
        public long userId { get; set; }
        public string email { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public Nullable<decimal> mobile { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
    
        public virtual tbl_UserProfile tbl_UserProfile1 { get; set; }
        public virtual tbl_UserProfile tbl_UserProfile2 { get; set; }
    }
}
