//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TSEntities : DbContext
    {
        public TSEntities()
            : base("name=TSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_SheetDetails> tbl_SheetDetails { get; set; }
        public virtual DbSet<tbl_SheetMaster> tbl_SheetMaster { get; set; }
        public virtual DbSet<tbl_UserLogin> tbl_UserLogin { get; set; }
        public virtual DbSet<tbl_UserProfile> tbl_UserProfile { get; set; }
        public virtual DbSet<tbl_ProductMaster> tbl_ProductMaster { get; set; }
    }
}
